{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.Base exposing (baseMetrics, getBadge, health, postWebhook, version)

import Data.Version exposing (Version, versionDecoder)
import Data.Build exposing (Build, buildDecoder)
import Data.Error exposing (Error, errorDecoder)
import Data.Webhook exposing (Webhook, webhookEncoder)
import Data.String exposing (Decode.string, String)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "http://localhost"


{-
   Retrieve metrics from the Vela api
-}
baseMetrics : Http.Request String
baseMetrics =
    { method = "GET"
    , url = basePath ++ "/metrics"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson Decode.string
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   Get a badge for the repo
-}
getBadge : String -> String -> Http.Request String
getBadge org repo =
    { method = "GET"
    , url = basePath ++ "/badge/" ++ org ++ "/" ++ repo ++ "/status.svg"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson Decode.string
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   Check if the Vela API is available
-}
health : Http.Request String
health =
    { method = "GET"
    , url = basePath ++ "/health"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson Decode.string
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   Deliver a webhook to the vela api
-}
postWebhook : Webhook -> Http.Request Build
postWebhook model =
    { method = "POST"
    , url = basePath ++ "/webhook"
    , headers = []
    , body = Http.jsonBody <| webhookEncoder model
    , expect = Http.expectJson buildDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   Get the version of the Vela API
-}
version : Http.Request Version
version =
    { method = "GET"
    , url = basePath ++ "/version"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson versionDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


