{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.Deployments exposing (createDeployment, getDeployment, listDeployments)

import Data.Deployment exposing (Deployment, deploymentDecoder)
import Data.Error exposing (Error, errorDecoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "http://localhost"


{-
   Create a deployment for the configured backend
-}
createDeployment : String -> String -> Http.Request Deployment
createDeployment org repo =
    { method = "POST"
    , url = basePath ++ "/api/v1/deployments/" ++ org ++ "/" ++ repo
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson deploymentDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   Get a deployment from the configured backend
-}
getDeployment : String -> String -> String -> Http.Request Deployment
getDeployment org repo deployment =
    { method = "GET"
    , url = basePath ++ "/api/v1/deployments/" ++ org ++ "/" ++ repo ++ "/" ++ deployment
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson deploymentDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   Get a list of deployments for the configured backend
-}
listDeployments : String -> String -> Http.Request (List Deployment)
listDeployments org repo =
    { method = "GET"
    , url = basePath ++ "/api/v1/deployments/" ++ org ++ "/" ++ repo
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson (Decode.list deploymentDecoder)
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


