{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.Queue exposing (info)

import Data.QueueInfo exposing (QueueInfo, queueInfoDecoder)
import Data.Error exposing (Error, errorDecoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "http://localhost"


{-
   Get queue credentials
-}
info : Http.Request QueueInfo
info =
    { method = "POST"
    , url = basePath ++ "/api/v1/queue/info"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson queueInfoDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


