{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.Schedules exposing (createSchedule, deleteSchedule, getSchedule, listSchedules, updateSchedule)

import Data.Schedule exposing (Schedule, scheduleDecoder, scheduleEncoder)
import Data.Error exposing (Error, errorDecoder)
import Data.String exposing (Decode.string, String)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "http://localhost"


{-
   Create a schedule in the configured backend
-}
createSchedule : String -> String -> Schedule -> Http.Request Schedule
createSchedule org repo model =
    { method = "POST"
    , url = basePath ++ "/api/v1/schedules/" ++ org ++ "/" ++ repo
    , headers = []
    , body = Http.jsonBody <| scheduleEncoder model
    , expect = Http.expectJson scheduleDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   Delete a schedule in the configured backend
-}
deleteSchedule : String -> String -> String -> Http.Request String
deleteSchedule org repo schedule =
    { method = "DELETE"
    , url = basePath ++ "/api/v1/repos/" ++ org ++ "/" ++ repo ++ "/" ++ schedule
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson Decode.string
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   Get a schedule in the configured backend
-}
getSchedule : String -> String -> String -> Http.Request Schedule
getSchedule org repo schedule =
    { method = "GET"
    , url = basePath ++ "/api/v1/schedules/" ++ org ++ "/" ++ repo ++ "/" ++ schedule
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson scheduleDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   Get all schedules in the configured backend
-}
listSchedules : String -> String -> Http.Request (List Schedule)
listSchedules org repo =
    { method = "GET"
    , url = basePath ++ "/api/v1/schedules/" ++ org ++ "/" ++ repo
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson (Decode.list scheduleDecoder)
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   Update a schedule for the configured backend
-}
updateSchedule : String -> String -> String -> Schedule -> Http.Request Schedule
updateSchedule org repo schedule model =
    { method = "PUT"
    , url = basePath ++ "/api/v1/schedules/" ++ org ++ "/" ++ repo ++ "/" ++ schedule
    , headers = []
    , body = Http.jsonBody <| scheduleEncoder model
    , expect = Http.expectJson scheduleDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


