{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.Scm exposing (syncRepo, syncReposForOrg)

import Data.Repo exposing (Repo, repoDecoder)
import Data.Error exposing (Error, errorDecoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "http://localhost"


{-
   Sync up scm service and database in the context of a specific repo
-}
syncRepo : String -> String -> Http.Request Repo
syncRepo org repo =
    { method = "PATCH"
    , url = basePath ++ "/api/v1/scm/repos/" ++ org ++ "/" ++ repo ++ "/sync"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson repoDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


{-
   Sync up repos from scm service and database in a specified org
-}
syncReposForOrg : String -> Http.Request (List Repo)
syncReposForOrg org =
    { method = "PATCH"
    , url = basePath ++ "/api/v1/scm/orgs/" ++ org ++ "/sync"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson (Decode.list repoDecoder)
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


