{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.Graph exposing (Graph, graphDecoder, graphEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   a node is a pipeline stage and its relevant steps. an edge is a relationship between nodes, defined by the 'needs' tag.
-}


type alias Graph =
    {     }


graphDecoder : Decoder Graph
graphDecoder =
    decode Graph



graphEncoder : Graph -> Encode.Value
graphEncoder model =
    Encode.object
        ]


