{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.PipelineStepSecretSlice exposing (PipelineStepSecretSlice, pipelineStepSecretSliceDecoder, pipelineStepSecretSliceEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   StepSecretSlice is the pipeline representation of the secrets block for a step in a pipeline.
-}


type alias PipelineStepSecretSlice =
    {     }


pipelineStepSecretSliceDecoder : Decoder PipelineStepSecretSlice
pipelineStepSecretSliceDecoder =
    decode PipelineStepSecretSlice



pipelineStepSecretSliceEncoder : PipelineStepSecretSlice -> Encode.Value
pipelineStepSecretSliceEncoder model =
    Encode.object
        ]


