{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.PipelineStepSecret exposing (PipelineStepSecret, pipelineStepSecretDecoder, pipelineStepSecretEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   StepSecret is the pipeline representation of a secret from a secrets block for a step in a pipeline.
-}


type alias PipelineStepSecret =
    {     }


pipelineStepSecretDecoder : Decoder PipelineStepSecret
pipelineStepSecretDecoder =
    decode PipelineStepSecret



pipelineStepSecretEncoder : PipelineStepSecret -> Encode.Value
pipelineStepSecretEncoder model =
    Encode.object
        ]


