{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.PipelineSecret exposing (PipelineSecret, pipelineSecretDecoder, pipelineSecretEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Secret is the pipeline representation of a secret from the secrets block for a pipeline.
-}


type alias PipelineSecret =
    {     }


pipelineSecretDecoder : Decoder PipelineSecret
pipelineSecretDecoder =
    decode PipelineSecret



pipelineSecretEncoder : PipelineSecret -> Encode.Value
pipelineSecretEncoder model =
    Encode.object
        ]


