{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.PipelineVolumeSlice exposing (PipelineVolumeSlice, pipelineVolumeSliceDecoder, pipelineVolumeSliceEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   VolumeSlice is the pipeline representation of the volumes block for a step in a pipeline.
-}


type alias PipelineVolumeSlice =
    {     }


pipelineVolumeSliceDecoder : Decoder PipelineVolumeSlice
pipelineVolumeSliceDecoder =
    decode PipelineVolumeSlice



pipelineVolumeSliceEncoder : PipelineVolumeSlice -> Encode.Value
pipelineVolumeSliceEncoder model =
    Encode.object
        ]


