{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.Pipeline exposing (Pipeline, pipelineDecoder, pipelineEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias Pipeline =
    {     }


pipelineDecoder : Decoder Pipeline
pipelineDecoder =
    decode Pipeline



pipelineEncoder : Pipeline -> Encode.Value
pipelineEncoder model =
    Encode.object
        ]


