{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.PipelineVolume exposing (PipelineVolume, pipelineVolumeDecoder, pipelineVolumeEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Volume is the pipeline representation of a volume from a volumes block for a step in a pipeline.
-}


type alias PipelineVolume =
    {     }


pipelineVolumeDecoder : Decoder PipelineVolume
pipelineVolumeDecoder =
    decode PipelineVolume



pipelineVolumeEncoder : PipelineVolume -> Encode.Value
pipelineVolumeEncoder model =
    Encode.object
        ]


