{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.PipelineUlimit exposing (PipelineUlimit, pipelineUlimitDecoder, pipelineUlimitEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Ulimit is the pipeline representation of a ulimit from the ulimits block for a step in a pipeline.
-}


type alias PipelineUlimit =
    {     }


pipelineUlimitDecoder : Decoder PipelineUlimit
pipelineUlimitDecoder =
    decode PipelineUlimit



pipelineUlimitEncoder : PipelineUlimit -> Encode.Value
pipelineUlimitEncoder model =
    Encode.object
        ]


