{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.PipelineRuleset exposing (PipelineRuleset, pipelineRulesetDecoder, pipelineRulesetEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Ruleset is the pipeline representation of a ruleset block for a step in a pipeline.
-}


type alias PipelineRuleset =
    {     }


pipelineRulesetDecoder : Decoder PipelineRuleset
pipelineRulesetDecoder =
    decode PipelineRuleset



pipelineRulesetEncoder : PipelineRuleset -> Encode.Value
pipelineRulesetEncoder model =
    Encode.object
        ]


