{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.PipelineContainer exposing (PipelineContainer, pipelineContainerDecoder, pipelineContainerEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Container is the pipeline representation of a Container in a pipeline.
-}


type alias PipelineContainer =
    {     }


pipelineContainerDecoder : Decoder PipelineContainer
pipelineContainerDecoder =
    decode PipelineContainer



pipelineContainerEncoder : PipelineContainer -> Encode.Value
pipelineContainerEncoder model =
    Encode.object
        ]


