{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.PipelineSecretSlice exposing (PipelineSecretSlice, pipelineSecretSliceDecoder, pipelineSecretSliceEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   SecretSlice is the pipeline representation of the secrets block for a pipeline.
-}


type alias PipelineSecretSlice =
    {     }


pipelineSecretSliceDecoder : Decoder PipelineSecretSlice
pipelineSecretSliceDecoder =
    decode PipelineSecretSlice



pipelineSecretSliceEncoder : PipelineSecretSlice -> Encode.Value
pipelineSecretSliceEncoder model =
    Encode.object
        ]


