{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.PipelineStage exposing (PipelineStage, pipelineStageDecoder, pipelineStageEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Stage is the pipeline representation of a stage in a pipeline.
-}


type alias PipelineStage =
    {     }


pipelineStageDecoder : Decoder PipelineStage
pipelineStageDecoder =
    decode PipelineStage



pipelineStageEncoder : PipelineStage -> Encode.Value
pipelineStageEncoder model =
    Encode.object
        ]


