{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.Schedule exposing (Schedule, scheduleDecoder, scheduleEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias Schedule =
    {     }


scheduleDecoder : Decoder Schedule
scheduleDecoder =
    decode Schedule



scheduleEncoder : Schedule -> Encode.Value
scheduleEncoder model =
    Encode.object
        ]


