{-
   Vela server
   API for the Vela server

   OpenAPI spec version: 0.23.2
   

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.Version exposing (Version, versionDecoder, versionEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   Version represents application information that follows semantic version guidelines from https://semver.org/.
-}


type alias Version =
    {     }


versionDecoder : Decoder Version
versionDecoder =
    decode Version



versionEncoder : Version -> Encode.Value
versionEncoder model =
    Encode.object
        ]


